[package]
name = "linter-markdown"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
linter.workspace = true
pulldown-cmark.workspace = true
serde.workspace = true

[dev-dependencies]
tempfile.workspace = true
