//! Rules which analyze Rust syntax and semantics.

mod accessor;
mod arguments;
mod blocking;
mod boolean;
mod boundary;
mod catchall;
mod ceremony;
mod command;
mod constructor;
mod contract;
mod duplicate;
mod environment;
mod function;
mod model;
mod naming;
mod nesting;
mod object;
mod placement;
mod receiver;
mod result;
mod role;
mod safety;
mod state;
mod toolkit;

pub use accessor::Bloat as AccessorBloat;
pub use arguments::ManualDispatch;
pub use blocking::AsyncBlocking;
pub use boolean::State as BooleanState;
pub use boundary::PathModules;
pub use catchall::CatchAllModule;
pub use ceremony::CeremonialStructure;
pub use command::PlatformCommand;
pub use constructor::Ownership as ConstructorOwnership;
pub use contract::BroadTrait;
pub use duplicate::Entity as DuplicateEntity;
pub use environment::Access as EnvironmentAccess;
pub use function::FreeFunction;
pub use model::Duplication as ModelDuplication;
pub use naming::StructNaming;
pub use nesting::MaximumNesting;
pub use object::GodObject;
pub use placement::IntegrationCandidate;
pub use receiver::Repetition as ReceiverRepetition;
pub use result::IgnoredResult;
pub use role::Suffix as SuffixRole;
pub use safety::Boundary as UnsafeBoundary;
pub use state::FiniteStateString;
pub use toolkit::GuiToolkitLeakage;
